### ISSUE TITLE
No sound/audio under some circumstances in OpenEmu 2.1

### ISSUE THREAD

**Issue by niostick** [OpenEmu/OpenEmu#4011]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step: i can´t hear the sound from the games. All worked before the update.
1. How to cause the problem: start any game and none of them have sounds. I have sound on my mac and i testet to play som music and it worked but not the game sound.

# Expected Behavior
Everything works perfect. 

# Observed Behavior
everything works but not the sound. 
# Debugging Information

- OpenEmu Version: 2.1
- macOS Version: 10.15

**Comment by clobber** [comment]
Test the build found here: https://github.com/OpenEmu/OpenEmu/issues/4008#issuecomment-546697028

**Comment by StevenZeng96** [comment]
I test it, but still no sound when playing NDS game.(But GBA games have it)

**Debugging Information** 
- Game: Legend of Zelda: Spirit Tracks & Ace Attorney 4
- AirPods & Dualshock 4 
- OpenEmu Version V2.1 274-gd2fc9b6-Release
- macOS Version 10.15 (19A602)

**Comment by clobber** [comment]
@StevenZeng96 Thanks for reporting! We have now solved most issues using Bluetooth and other secondary audio output devices, which will be available in the next bugfix release. We can also confirm there is a problem in particular with NDS games (DeSmuME core) which we are still investigating. When resolved, I will link you a test build in this issue.

**Comment by clobber** [comment]
@StevenZeng96 Okay. Part of the the issue regarding Bluetooth audio for NDS games has been resolved with a DeSmuME core plugin update, but you will also need the latest test build of OpenEmu for the full fix: https://transfer.sh/EEUZs/OpenEmu_test2.zip

**Comment by StevenZeng96** [comment]
Awesome! I just test it, Everything is great now. Thanks for your work😬

**Comment by wagenet** [comment]
@clobber my apologies for the possible duplicate issue (#4016). I had searched a couple of days ago and not seen any similar issue. I unintentionally neglected to search again when I decided to create the new issue yesterday. I will try out the new build and see if it resolves my issue.

**Comment by thepmaar** [comment]
I had recently noticed the same audio issue after upgrading to 2.1, but for me the issue is with no sound coming out of a Multi-Output Device. I have tried the test build just now and the issue is still there. I have no Bluetooth speakers, but I also tried HDMI audio, which works on both builds.

Let me know what other info you'll need, I'm new at this. Thanks.

**Comment by thepmaar** [comment]
And sorry, it also works on both builds using Headphones output.

**Comment by clobber** [comment]
> Multi-Output Device

Please elaborate in detail. What is your setup and how would we test it?

**Comment by thepmaar** [comment]
My Multi-Output Device consists of Built-in Output, SB X-Fi Surround 5.1 Pro (USB), Soundflower (2ch) and HDMI. The SB X-Fi Surround 5.1 Pro is the master device, set at 96.0 kHZ.

I should note that the SB X-Fi Surround 5.1 Pro output on its own does not produce any sound in OpenEmu either, on both builds, making me just realize now it may be the USB audio that could be the issue.

**Comment by stuartcarnie** [comment]
@thepmaar I set up a multi-output device and confirmed it works in OpenEmu, Apple Music, and other system alerts. Can you confirm your setup plays correctly outside of OpenEmu?

**Comment by thepmaar** [comment]
> @thepmaar I set up a multi-output device and confirmed it works in OpenEmu, Apple Music, and other system alerts. Can you confirm your setup plays correctly outside of OpenEmu?

Yes, I can confirm my multi-output device works fine on other apps such as Swinsian, Vivaldi, VLC and more, as well as system alerts.

**Comment by wagenet** [comment]
@clobber the new build fixes my issue. Thanks!

**Comment by Gougere89** [comment]
I think it is related to my issue. 
Everytime I launch a game since I updated, no sound. I am using a Sennheiser HD 4.40 BT 
Tried on PC-Engine, SNES, GBA and Atari 2600. 

It only worked once, but my Bluetooth headphones automaticaly turned into "Call" mode.
So playing a game with phone call-like sound... Not that good. :)

I see a performance increase and new great shaders though! :D

**Comment by clobber** [comment]
@Gougere89 Thanks, but there is a test built you neglected to mention if you tried or not:

https://github.com/OpenEmu/OpenEmu/issues/4011#issuecomment-548220899

**Comment by clobber** [comment]
The major issues with Bluetooth and other audio output devices is now resolved with OpenEmu 2.1.1. There may still be some edge cases with more complex setups, but this is the best audio is going to be for now.
