### ISSUE TITLE
macOS 13.0 Ventura upgrade stops fast-forward from working

### ISSUE THREAD

**Issue by jzide5509** [OpenEmu/OpenEmu#4780]
When fast-forwarding GBA games after the Ventura upgrade, the fastforward function no longer works. The icon still appears in the top left of the screen but there is no discernible impact.

# Steps to reproduce

1. Upgrade to MacOS 13.0 Ventura
2. Attempt to fast-forward

# Expected Behavior

The game to fast-forward when the fast-forward key is pressed.

# Observed Behavior

The fast-forward icon appears but the game's speed remains at 1.0

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: 13.0 ventura

**Comment by jonashferreira** [comment]
Same scenario for me, just adding that N64 emulator FF is working properly, but PSOne and GBA don't. I will test more emulators!

**Comment by ShawZam** [comment]
same issue in other cores, NDS is no longer fast forwarding. Seems like a shader based issue though as SABR shader will allow you to fast forward in GBA games

**Comment by Abbatron** [comment]
I checked, using the SABR shader makes it work on NDS as well

**Comment by KirkSpaziani** [comment]
Seeing this on Genesis especially

**Comment by clobber** [comment]
>Seems like a shader based issue

And what is the shader causing the problem?

**Comment by dvessel** [comment]
Can’t recreate it in GBA or the PS1 or any of the cores. Checked with all the built-in shaders.

Ventura 13.1 Beta (had no issues with 13 either).

**Comment by sundowns** [comment]
Encountering this too for Nintendo DS emulation. Updated to Ventura and fast forward no longer works, though it indicates that it should be working with the icon fast-forward icon appearing.

M2 Macbook Air 16GB, Ventura 13.0

**Comment by sleeper0926** [comment]
Same thing happened to me. NDS and PS1 emulation does not fast-forward even though the fast-forward icon appeared at the top left of screen. Interestingly, PSP emulation fast forward still works. Please help! (M1 MacMini, Ventura 13.0.)

**Comment by karlingen** [comment]
+1

**Comment by maxdemaio** [comment]
+1 @karlingen 

I am experiencing the same issue as well 👍🏻 I am able to set the fast-forward button, see the icon when pressed, but the fast-forwarding does not occur when used.

Chip: M1
RAM: 16GB
macOS: Ventura 13.0

**Comment by SilenceR316** [comment]
Same issue here as well with similar specs to you all. Just did an software update but still no luck :(. 


> +1 @karlingen @jzide5509
> 
> I am experiencing the same issue as well 👍🏻 I am able to set the fast-forward button, see the icon when pressed, but the fast-forwarding does not occur when used. This is on the GBA emulator.
> 
> OpenEmu Version: 2.3.3 Chip: M1 RAM: 16GB macOS: Ventura 13.0
> 
> edit: there's an update to macOS 13.0.1 tonight so I'll try that

**Comment by maxdemaio** [comment]
Hm yeah I'm not sure if we'd be able to fix it without a code change. I was trying to understand how it's done and see there's a boolean variable named `isFastForwarding` in [OpenEmu/OEGameLayerNotificationView.swift](./OpenEmu/OEGameLayerNotificationView.swift):

```swift
lazy var fastForwardImage   = NSImage(named: "hud_fastforward_notification")
// ...
var isFastForwarding: Bool  = false
var isRewinding: Bool       = false
```

**Comment by karlingen** [comment]
> Hm yeah I'm not sure if we'd be able to fix it without a code change. I was trying to understand how it's done and see there's a boolean variable named `isFastForwarding` in [OpenEmu/OEGameLayerNotificationView.swift](./OpenEmu/OEGameLayerNotificationView.swift):
> 
> ```swift
> lazy var fastForwardImage   = NSImage(named: "hud_fastforward_notification")
> // ...
> var isFastForwarding: Bool  = false
> var isRewinding: Bool       = false
> ```
> 
> I imagine though we'd have to look at the GBA core itself? Which is located here https://github.com/OpenEmu/mGBA-Core/. Seems like the one OpenEmu is using, `0.8.4`, might be outdated with the most recently released version, `0.10.0` (per https://mgba.io/). I know some of you mentioned there could be an issue with the "shaders" so we could look there too.

I also tried to take a quick stab at this and came to the same conclusion.
There's something in the underlying core - perhaps some unofficial code in the previous macOS SDK that is no longer public in Ventura.

**Comment by karlingen** [comment]
UPDATE: Fast-forward works with the shader called **VT220**

<img width="722" alt="image" src="https://user-images.githubusercontent.com/2265452/201500911-749e781a-2354-4b29-bd1a-eb6390c516f5.png">

**Comment by maxdemaio** [comment]
@karlingen by default I don't see this shader, but I noticed the only one for me that worked is `CRT Geom` although this is not the prettiest shader in my opinion. I think by default `Pixelate` is chosen. Personally, I like to use `Nearest Neighbor`. 

So perhaps this is a shader issue? I wonder what's going on with why these 2 CRT shaders work and the others don't.

**Comment by karlingen** [comment]
@clobber @dvessel Seems like it IS shader related. Do you mind checking if you can repro on the default shader, Pixelate, please?

**Comment by karlingen** [comment]
> @karlingen by default I don't see this shader, but I noticed the only one for me that worked is `CRT Geom` although this is not the prettiest shader in my opinion. I think by default `Pixelate` is chosen. Personally, I like to use `Nearest Neighbor`.
> 
> So perhaps this is a shader issue? I wonder what's going on with why these 2 CRT shaders work and the others don't.

Another interesting discovery: For me, `CRT Geom` only works if I set Scale to `5x`

**Comment by maxdemaio** [comment]
> @clobber @dvessel Seems like it IS shader related. Do you mind checking if you can repro on the default shader, Pixelate, please?

I tried everything and none work besides `CRT Geom` but even then it's a little buggy. I think we can confirm it has to do with the shaders and how they interact with whatever fast-forward function we have going on the mGBA backend. I still think looking into a mGBA version upgrade would be good.

Not sure what the scope of upgrading would be because it looks like we fork mGBA's repo but then format to be compatible with OpenEmu.

**Comment by dvessel** [comment]
@maxdemaio fast forward and rewind works for all cores and shaders I’ve tested. The only thing that broke for me in Ventura is the Dolphin core.

I don’t think this is related since OpenEmu was working since RC 1 but I’m currently on Version 13.1 Beta (22C5044e).

**Comment by maxdemaio** [comment]
> @maxdemaio fast forward and rewind works for all cores and shaders I’ve tested. The only thing that broke for me in Ventura is the Dolphin core.
> 
> I don’t think this is related since OpenEmu was working since RC 1 but I’m currently on Version 13.1 Beta (22C5044e).

@dvessel Hm in that case I will try to see if I can upgrade to macOS Ventura `13.1` and restart. I think most of us are on `13.0.0` or `13.0.1` from the most recent update.

**Comment by karlingen** [comment]
> > @maxdemaio fast forward and rewind works for all cores and shaders I’ve tested. The only thing that broke for me in Ventura is the Dolphin core.
> > I don’t think this is related since OpenEmu was working since RC 1 but I’m currently on Version 13.1 Beta (22C5044e).
> 
> @dvessel Hm in that case I will try to see if I can upgrade to macOS Ventura `13.1` and restart. I think most of us are on `13.0.0` or `13.0.1` from the most recent update. I'm not actually sure how to get a specific version installed on my Mac though so will have to research 👍🏻 Only thing I found was:
> 
> ```batchfile
> softwareupdate --list-full-installers
> ```
> 
>  ```
> Finding available software
> Software Update found the following full installers:
> * Title: macOS Ventura, Version: 13.0.1, Size: 11866460KiB, Build: 22A400, Deferred: NO
> * Title: macOS Ventura, Version: 13.0, Size: 11866804KiB, Build: 22A380, Deferred: NO
> ```

It's a Beta version, so you will have to sign up for the Beta releases here: https://beta.apple.com/sp/betaprogram

**Comment by maxdemaio** [comment]
@karlingen Any luck on your end if you tried the upgrade to RC 2 (13.1) at all? I'll try and get this going on my end too.

**Comment by maxdemaio** [comment]
Another crazy suggestion of mine:

I can see we are using the commit `ccc637a2b5c2593cd64e679ac10612780d452b52` for our mGBA core. This commit is for version `0.8.4`. But, that is not the latest commit on the repo. In fact, @clobber has done some amazing work to bump it to mGBA version `0.9.2` on the main branch.

Since we're able to compile OpenEmu manually, my though is you could actually bring in the mGBA core that is on `2cc9e601ce376aaa4bb8f918d20f67956dbc278c`, with version `0.9.2`.

**Comment by clobber** [comment]
@maxdemaio Enough with this. The problem has nothing to do with the core plugins.

**Comment by stuartcarnie** [comment]
Can I ask if everyone is running an external display? Try running on your built-in display, if not.

**Comment by dvessel** [comment]
I wasn’t having the problem but I was also using a variable refresh rate or _ProMotion_. When in a fixed refresh rate, it won’t fast forward. It’ll occasionally speed up for a split second then settle back to the limit set by the refresh rate.

**Comment by samiralalami** [comment]
I tried a lot of methods to get the DS fast forward to make it work. Changed the shader, tired updating to 13.1 on my MacBook, and no dice.

Any idea how to fix this issue?
