### ISSUE TITLE
Keyboard stopped working, changing permissions doesn't help

### ISSUE THREAD

**Issue by nathanielvirgo** [OpenEmu/OpenEmu#5020]
I used OpenEmu last night, but today it is not recognising the keyboard. I have not done anything in between that should affect this. It doesn't give me any error message, but pressing keys on the keyboard simply has no effect.

I have never used a controller with it, so it is not related to that.

I have tried:

 * go into System Preferences -> Security & Privacy -> Privacy -> Input Monitoring and toggle the OpenEmu checkbox
 * go into ... -> Input Monitoring, remove OpenEmu entirely, then re-add it
 * uncheck the checkbox, start OpenEmu, then check the checkbox when it prompts me
 * remove OpenEmu entirely from Input Monitoring, start OpenEmu, then add it back (for some reason it didn't prompt me in this case)

I have not tried:

 * reinstalling OpenEmu - I also don't know how to safely do it without losing my game state data
 * rebooting the machine - I'd rather avoid this if I possibly can

What can I do to get it working again without losing my game state data?

**Comment by nathanielvirgo** [comment]
...and then a few hours later it started working again. I didn't do anything.

**Comment by SiriusDarkblaze** [comment]
> ...and then a few hours later it started working again. I didn't do anything.

I will always say rebooting a Mac is necessary at least once a week, if you don't then unexpected things can occur, that being said, macOS Security and Privacy for input monitoring has been, shall we say odd, for a long time and this can just randomly happen.

**Comment by nathanielvirgo** [comment]
I never reboot my mac except to install security updates - I run it for months at a time usually, with no ill effects.

**Comment by PeterL12** [comment]
I have the same problem, and I have tried to restart my computer, delete all tabs, delete all apps that could interfere with open emu, trying to type some stuff Github said to in terminal.app, etc. Nothing is changing and it is very frustrating. I need some help

**Comment by rannsaka** [comment]
Same here. I ended up just deleting and reinstalling an older version (2.3.3) and it works great. It's a shame that this has been an issue since launch of 2.4 back in January and the devs still haven't addressed it. Get what you pay for, I guess.

**Comment by PeterL12** [comment]
Where did you reinstall Open Emulator? I'm a bit stressed since I can't even move in the past games I have played. All my progress... I wouldn't like if it was lost. If anyone has any other solutions/ideas, it would be helpful.

**Comment by rannsaka** [comment]
I just reinstalled the old fashioned way. Deleted the app from Applications folder, then dragged over the new one into Applications folder. All of my games, saves and settings were retained, since those are in the application support folder, which doesn't get deleted when the app does.

**Comment by rannsaka** [comment]
Actually never mind, I tried this fix and It worked with me:

1. Trash any older copy of Openemu and empty trash can

2. Go to Apple menu > System Settings > Privacy & Security  > Input Monitoring on the right.

3. Select Openemu

4. Press on the minus sign to remove OpenEmu from the list

5. Download and Install a fresh copy of OpenEmu

6. Run it and follow instructions.

**Comment by PeterL12** [comment]
That's great advice, do you happen to have the link you downloaded it from?

**Comment by PeterL12** [comment]
Also, do I need to delete the past Open Emu, since there I have the games I have played with all my progress?

**Comment by rannsaka** [comment]
@PeterL12 Follow the 6 step process in my last post and it should fix the issue for you. Game data will be retained, as I said.

**Comment by AjaniStewart** [comment]
> @PeterL12 Follow the 6 step process in my last post and it should fix the issue for you. Game data will be retained, as I said.

In case anyone else is running into this issue, this worked for me

**Comment by torriep** [comment]
After the update, my mouse was recognized but not my keyboard.  What fixed it was to remove openEMU from the Monitoring input list on my MAC 14.5. et add it back.  I rebooted and also closed open emu and now everything works

**Comment by cjulberto** [comment]
> Actually never mind, I tried this fix and It worked with me:
> 
> 1. Trash any older copy of Openemu and empty trash can
> 2. Go to Apple menu > System Settings > Privacy & Security  > Input Monitoring on the right.
> 3. Select Openemu
> 4. Press on the minus sign to remove OpenEmu from the list
> 5. Download and Install a fresh copy of OpenEmu
> 6. Run it and follow instructions.

WORKKKK !!!!!
WORKKKK !!!!!
WORKKKK !!!!!
WORKKKK !!!!!
WORKKKK !!!!!
WORKKKK !!!!!.

THANKS SO MUCH BRO ! I LOVE YOU , LOL

**Comment by ProfessorRemoWilliams** [comment]
Keyboard went out several OS updates ago, now on Sequoia with intel Macbook Pro. Tried recommended fixes, still not working.

**Comment by MommysMilkers** [comment]
I've had the same problem, none of the recommended fixes have worked. I've tried uninstalling, reinstalling. Restarting my Mac, everything. Currently on Sonama 14.7
